# Generated by Django 4.1.7 on 2023-04-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appliedjob_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='student_username',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
